FROM golang:1.24-alpine

WORKDIR /app

RUN apk add build-base gcc-go musl-dev
RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

#Install build essentials
# RUN apk add --no-cache gcc musl-dev
RUN apk --no-cache add ca-certificates tzdata

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .
